### ISSUE TITLE
$screen-sm of 550px seems incompatible with container width

### ISSUE THREAD

**Issue by sheldond** [CruGlobal/crubrand#26]
Hi @thejamesdempsey! I'm using crubrand on a project for Cru.

In the commit 68f8cd61ec18c8404147d0256d009fcb466f2602 the $screen-sm breakpoint was decreased, this seems to cause a problem because the container width is larger than the page width (see screenshot). 

I think the container width would have to be updated to something like this:
```
$container-sm:            (520px + $grid-gutter-width);
```

Unfortunately this makes the page look a bit funny because it's so narrow. My suggestion would be to simply revert $screen-sm back to the bootstrap standard of 768px, what do you think?

Thanks!
Sheldon

![screen shot 2015-05-06 at 17 01 38](https://cloud.githubusercontent.com/assets/149429/7503844/7d1c86e2-f413-11e4-80dd-9d357276b95f.png)

**Comment by thejamesdempsey** [comment]
This breakpoint was changed because it forces small screen content on screens that are not necessarily small. I think as a universal setting we would like to leave the breakpoint as it is, not the default of `768px`. Can I take a look at the project you are working on? If I can see that I can recommend the best course of action

**Comment by sheldond** [comment]
Thanks for the reply! Yes you can see the project up at http://godtools.ballistiq.com with source at https://github.com/Indigitous/godtools-web

**Comment by sheldond** [comment]
Hi @thejamesdempsey, I was able to work around some of the other css issues that we ran into, however this breakpoint issue is more tricky. We can't modify the breakpoints unless we use a fork of crubrand, which I prefer not to do.

Are you open to adding the `!default` flag to the variable definitions in https://github.com/CruGlobal/crubrand/blob/master/_overrides.scss? this would allow us to override the variables and create our own breakpoints. I think it could make crubrand more extensible and useful for all including projects, without affecting the default variables. If you think this is okay I could submit a pull request.

Please let me know, thanks!

**Comment by thejamesdempsey** [comment]
@sheldond I would be okay with the `!default` flag although it should be just as easy to override the variable without that flag. You will need to make a separate place for your variables so you can override it there.

**Comment by sheldond** [comment]
@thejamesdempsey thanks, interesting! Do you mind explaining how I would override it today? Perhaps I'm missing something simple! 

My scss looks like this. This doesn't work, but if `!default` was used then it would work:
```
$screen-sm: 768px;
@import "crubrand/crubrand";
```

**Comment by thejamesdempsey** [comment]
Try:

```
@import "crubrand/crubrand";
$screen-sm: 768px;
```

**Comment by sheldond** [comment]
Thanks! Unfortunately that doesn't seem to be working, it seems the css rules that depend on `$screen-sm` are defined when `@import "crubrand/crubrand";` is called, so changing the variable later has no effect.  :persevere:

**Comment by thejamesdempsey** [comment]
Yeah you are correct. I was messing around with a few different ways to do it. If you import individual files to a project stylesheet from crubrand that method will work, but if you import the entire project it does not. Go ahead and submit a PR for the `!default` value if you wish.

**Comment by sheldond** [comment]
@thejamesdempsey thanks! Unfortunately I discovered a problem with my proposed solution of using `!default`: the crubrand values in `_overrides.scss` would be ignored because the values in `../bootstrap-sass-official/assets/stylesheets/bootstrap/variables` are included first. Trying to fix this by swapping the include order doesn't work because of dependencies. I may have to leave this alone for now, but I certainly appreciated your help!

**Comment by elikem** [comment]
@sheldond you can reopen this if you need to.
