### ISSUE TITLE
label-info is hard to read

### ISSUE THREAD

**Issue by OzzieOrca** [CruGlobal/crubrand#36]
The info label is really hard to read with white text on light blue background:
<img width="312" alt="screen shot 2015-10-05 at 10 49 22 am" src="https://cloud.githubusercontent.com/assets/756501/10283699/cbef891a-6b4e-11e5-92cb-f2c4be4c7b9a.png">
<img width="125" alt="screen shot 2015-10-05 at 10 50 54 am" src="https://cloud.githubusercontent.com/assets/756501/10283741/0213ea7c-6b4f-11e5-8af5-8eecf7141ab2.png">

```
<span class="label label-info">Info</span>
```
I don't think it looks much better with black text although it is readable. If you've got a bunch of them the info one looks out of place:
<img width="313" alt="screen shot 2015-10-05 at 10 47 40 am" src="https://cloud.githubusercontent.com/assets/756501/10283653/91658ba0-6b4e-11e5-9adf-0bc394ba5885.png">

**Comment by mattgasior** [comment]
@OzzieOrca – looking at our styleguide, it looks like we have a different color for our info buttons than our info text. That's likely a mistake.

[![screenshot](https://cloud.githubusercontent.com/assets/5825545/10288658/48486f90-6b68-11e5-9735-00463b56ab09.png)](http://cruglobal.github.io/cru-web-styleguide/styleguide/ui-components/buttons/#options)

Let me look at the SASS and see why that's not picking up the same color.

**Comment by elikem** [comment]
@OzzieOrca looks like what @mattgasior is correct about our color scheme being different from the results you are getting. 

I setup a [sample project](googledrive.com/host/0B2QjE1x_RoflbUxwT1p6UWJLTzg) with crubrand. You can also download the [project folder](https://drive.google.com/open?id=0B2QjE1x_RoflbUxwT1p6UWJLTzg) as well.

**Comment by OzzieOrca** [comment]
Thanks! This seems to be fixed by: https://github.com/CruGlobal/crubrand/commit/af234d8ae2bd5d4bdf3fb321c7b01582901882bb

I didn't see that anything had been done at first.
